package bolsavalores;
import java.awt.event.ItemEvent;
import javax.swing.JFileChooser;
import java.io.*;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;

public class VentanaPrincipal extends javax.swing.JFrame
{
    //Declaracion de Variables
    Configuracion cfg;
    public DValores DatosValores;
    public DHistoricos DatosHistoricos;
    String NombreValor;
    int RedondeoValor;
    int NumeroValores;

    public VentanaPrincipal()
    {
        initComponents();
        
        //Inicializamos el Grill de Datos Historicos
        reiniciarJTable(TablaHistorica);

        //Cargamos el Fichero de Configuracion
        cfg = new Configuracion();
        cfg.CargarCFG("Bolsa.cfg");

        System.out.println("Fin de Fichero de Configuracion");

        //Declaro Variables
        DatosValores = new DValores(cfg.MaximoValores);
        DatosHistoricos = new DHistoricos(cfg.MaximoValores);
        
        //Cargamos lo Combos con los Rangos de dias establecidos en el CFG
        cfg.CargaBox(GraficoDias);
        cfg.CargaBox(TecnicoDias);

        //Si hemos Definido un Numero Maximo de Valores
        if (cfg.MaximoValores > 0)
        {
            //Cargamos Todos los Nombres de los Valores Almacenados
            DatosValores.CargaFichValores(cfg.RutaDatos, cfg.FicheroValores, cfg.Redondeo);

            //Si Tenemos Algun Dato Cargado
            if (DatosValores.NumeroValores > 0)
            {
                //Cargamos el Check Box de los Valores
                DatosValores.RellenaCombo(ListaValores);

                //Nos Posicionamos en el Primer Valor
                PosicionarseEnValorNum(0);
            }
        }
        //Establecemos la Activacion y Desactivacion de Botones
        ActivaDesactivaBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActLocal = new javax.swing.JButton();
        Insertar = new javax.swing.JButton();
        ListaValores = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        URLDatos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tecnico = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHistorica = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        panelGrafico = new javax.swing.JPanel();
        lblGrafico = new javax.swing.JLabel();
        BMostrarGrafico = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        GraficoDias = new javax.swing.JComboBox();
        ChkCierre = new javax.swing.JCheckBox();
        ChkMaximo = new javax.swing.JCheckBox();
        ChkMinimo = new javax.swing.JCheckBox();
        ChkS2 = new javax.swing.JCheckBox();
        ChkS1 = new javax.swing.JCheckBox();
        ChkPivotP = new javax.swing.JCheckBox();
        ChkR1 = new javax.swing.JCheckBox();
        ChkR2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TecnicoS2 = new javax.swing.JTextField();
        TecnicoS1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TecnicoPP = new javax.swing.JTextField();
        TecnicoR1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TecnicoR2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TecnicoFecha = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ValorActual = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ValorMaximo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ValorMinimo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        TecnicoDias = new javax.swing.JComboBox();
        Eliminar = new javax.swing.JButton();
        ActManual = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ActURL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bolsa Facil");

        ActLocal.setText("Fichero");
        ActLocal.setEnabled(false);
        ActLocal.setMargin(new java.awt.Insets(2, 5, 2, 5));
        ActLocal.setName(""); // NOI18N
        ActLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActLocalActionPerformed(evt);
            }
        });

        Insertar.setText("+");
        Insertar.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        ListaValores.setEditable(true);
        ListaValores.setToolTipText("");
        ListaValores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaValoresItemStateChanged(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("URL Datos");

        Tecnico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TablaHistorica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha", "Cierre", "Máximo", "Mínimo", "Variación", "%Var", "S2", "S1", "PivotP", "R1", "R2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaHistorica);
        TablaHistorica.getColumnModel().getColumn(0).setPreferredWidth(120);
        TablaHistorica.getColumnModel().getColumn(1).setPreferredWidth(70);
        TablaHistorica.getColumnModel().getColumn(2).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(3).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(4).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(5).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(6).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(7).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(8).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(9).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(10).setPreferredWidth(50);
        TablaHistorica.getColumnModel().getColumn(11).setPreferredWidth(50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tecnico.addTab("Históricos", jPanel1);

        panelGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraficoLayout.createSequentialGroup()
                .addComponent(lblGrafico)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraficoLayout.createSequentialGroup()
                .addComponent(lblGrafico)
                .addGap(0, 385, Short.MAX_VALUE))
        );

        BMostrarGrafico.setText("Cargar");
        BMostrarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMostrarGraficoActionPerformed(evt);
            }
        });

        jLabel3.setText("Gráfico");

        GraficoDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "25", "40", "70", "200", "250" }));

        ChkCierre.setSelected(true);
        ChkCierre.setText("Cierre");
        ChkCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkCierreActionPerformed(evt);
            }
        });

        ChkMaximo.setText("Máximo");
        ChkMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkMaximoActionPerformed(evt);
            }
        });

        ChkMinimo.setText("Mínimo");
        ChkMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkMinimoActionPerformed(evt);
            }
        });

        ChkS2.setText("S2");
        ChkS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkS2ActionPerformed(evt);
            }
        });

        ChkS1.setText("S1");
        ChkS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkS1ActionPerformed(evt);
            }
        });

        ChkPivotP.setText("PivotP");
        ChkPivotP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkPivotPActionPerformed(evt);
            }
        });

        ChkR1.setText("R1");
        ChkR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkR1ActionPerformed(evt);
            }
        });

        ChkR2.setText("R2");
        ChkR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GraficoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BMostrarGrafico)
                        .addGap(18, 18, 18)
                        .addComponent(ChkCierre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChkMaximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChkMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(ChkR2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChkR1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChkPivotP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChkS1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChkS2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GraficoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMostrarGrafico)
                    .addComponent(ChkCierre)
                    .addComponent(ChkMaximo)
                    .addComponent(ChkMinimo)
                    .addComponent(ChkS2)
                    .addComponent(ChkS1)
                    .addComponent(ChkPivotP)
                    .addComponent(ChkR1)
                    .addComponent(ChkR2))
                .addContainerGap())
        );

        Tecnico.addTab("Gráfica", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Soporte 2");

        TecnicoS2.setEditable(false);

        TecnicoS1.setEditable(false);

        jLabel6.setText("Soporte 1");

        jLabel9.setText("Pivot Point");

        TecnicoPP.setEditable(false);

        TecnicoR1.setEditable(false);

        jLabel8.setText("Resistencia 1");

        jLabel7.setText("Resistencia 2");

        TecnicoR2.setEditable(false);

        jLabel13.setText("Fecha:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TecnicoS2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TecnicoR2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TecnicoPP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TecnicoR1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TecnicoS1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TecnicoFecha)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TecnicoFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TecnicoR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TecnicoR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TecnicoPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TecnicoS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TecnicoS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Valor Actual");

        jLabel11.setText("Máximo");

        jLabel12.setText("Mínimo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValorActual, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValorMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValorMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ValorActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ValorMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(ValorMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TecnicoDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TecnicoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(TecnicoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        Tecnico.addTab("Datos Técnicos", jPanel3);

        Eliminar.setText("-");
        Eliminar.setEnabled(false);
        Eliminar.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        ActManual.setText("Manual");
        ActManual.setEnabled(false);
        ActManual.setMargin(new java.awt.Insets(2, 5, 2, 5));
        ActManual.setName(""); // NOI18N
        ActManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActManualActionPerformed(evt);
            }
        });

        jLabel4.setText("Incluir Datos");

        ActURL.setText("URL");
        ActURL.setEnabled(false);
        ActURL.setMargin(new java.awt.Insets(2, 5, 2, 5));
        ActURL.setName(""); // NOI18N
        ActURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActURLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tecnico)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaValores, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Insertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(URLDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActURL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActManual)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActLocal)
                    .addComponent(ListaValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Insertar)
                    .addComponent(URLDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Eliminar)
                    .addComponent(ActManual)
                    .addComponent(jLabel4)
                    .addComponent(ActURL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tecnico))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ActivaDesactivaBotones()
    {
        //Desactivamos Todos por Defecto
        Eliminar.setEnabled(false);
        ActLocal.setEnabled(false);
        ActManual.setEnabled(false);
        ActURL.setEnabled(false);
        Insertar.setEnabled(false);
        
        //Si hay Marcado algun Valor en el Combo
        if (!NombreValor.equals(""))
        {
            //Si el Nombre del Valor ya Existe
            if (DatosValores.BuscarValor(NombreValor) != -1)
            {
                Eliminar.setEnabled(true);
                ActLocal.setEnabled(true);
                ActManual.setEnabled(true);
                
                //Si la URL esta Indicada
                if (!URLDatos.getText().equals(""))
                    ActURL.setEnabled(true);
            }
            //Si el Nombre del Valor No Existe
            else
                Insertar.setEnabled(true);
        }
    }
    
    private void ActLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActLocalActionPerformed

        String NombreFichero;
        JFileChooser fc = new JFileChooser();

        //Mostrar la ventana para abrir archivo
        int respuesta = fc.showOpenDialog(this);

        //Comprobar si se ha pulsado Aceptar
        if (respuesta == JFileChooser.APPROVE_OPTION)
        {
            //Crear un objeto File con el archivo elegido
            File archivoElegido = fc.getSelectedFile();

            //Obtenemos la Ruta + Nombre del Fichero
            NombreFichero = archivoElegido.getPath();
            
            //Abrimos el Fichero
            if (DatosHistoricos.IncluirHistoricosLocal(NombreFichero, NombreValor, RedondeoValor) == true)
            {
                DatosHistoricos.CargaGrill(TablaHistorica);
                RellenaTecnico();
            }
        }
    }//GEN-LAST:event_ActLocalActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed

        //Comprobamos que el Valor no Exista en Memoria
        if (DatosValores.BuscarValor(NombreValor) == -1)
        {
            //Incluimos el Nuevo Valor en Memoria
            DatosValores.IncluirNuevoValor(NombreValor, URLDatos.getText(), RedondeoValor);

            //Actualizamos el Combo con los Datos de Memoria
            DatosValores.RellenaCombo(ListaValores);

            //Seleccionamos de Nuevo el Valor Incluido
            PosicionarseEnValorNom(NombreValor);
        }
        else
            System.out.println("El valor '"+NombreValor+"' ya Existe en Memoria");
        
        //Establecemos la Activacion y Desactivacion de Botones
        ActivaDesactivaBotones();
    }//GEN-LAST:event_InsertarActionPerformed

    private void PosicionarseEnValorNom(String PE_NombreValor)
    {
        //Buscamos la Posicion del Valor
        int Posicion = DatosValores.BuscarValor(PE_NombreValor);

        //Posicionamos el Combo Box
        ListaValores.setSelectedIndex(Posicion);
        URLDatos.setText(DatosValores.Matrix[Posicion].URLHistorico);
        NombreValor   = PE_NombreValor;
        RedondeoValor = DatosValores.Matrix[Posicion].Redondeo;

        //Si hemos Definido un Numero Maximo de Valores
        if (cfg.MaximoHistoricos > 0)
        {
            //Cargamos los Datos Historicos del Valor
            if (DatosHistoricos.IncluirHistoricosMemoria(cfg.RutaDatos, NombreValor, RedondeoValor))
            {
                DatosHistoricos.CargaGrill(TablaHistorica);
                RellenaTecnico();
            }
        }
    }
            
    private void PosicionarseEnValorNum(int PE_Posicion)
    {
        //Posicionamos el Combo Box
        ListaValores.setSelectedIndex(PE_Posicion);        
        URLDatos.setText(DatosValores.Matrix[PE_Posicion].URLHistorico);
        NombreValor   = DatosValores.Matrix[PE_Posicion].NombreValor;
        RedondeoValor = DatosValores.Matrix[PE_Posicion].Redondeo;
        
        //Si hemos Definido un Numero Maximo de Valores
        if (cfg.MaximoHistoricos > 0)
        {
            //Cargamos los Datos Historicos del Valor
            if (DatosHistoricos.IncluirHistoricosMemoria(cfg.RutaDatos, NombreValor, RedondeoValor))
            {
                DatosHistoricos.CargaGrill(TablaHistorica);
                RellenaTecnico();
            }                
        }
    }
    
    private void RellenaTecnico()
    {
        TecnicoFecha.setText(DatosHistoricos.Matrix[0].Fecha);
        TecnicoR2.setText(String.valueOf(DatosHistoricos.Matrix[0].R2));
        TecnicoR1.setText(String.valueOf(DatosHistoricos.Matrix[0].R1));
        TecnicoPP.setText(String.valueOf(DatosHistoricos.Matrix[0].PivotPoint));
        TecnicoS1.setText(String.valueOf(DatosHistoricos.Matrix[0].S1));
        TecnicoS2.setText(String.valueOf(DatosHistoricos.Matrix[0].S2));
    }
    
    private void ListaValoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaValoresItemStateChanged
        
        //Una vez Desmarcado el Valor Seleccionado
        if (evt.getStateChange() == ItemEvent.DESELECTED)
        {   
            System.out.println("ListaValoresItemStateChanged: "+NombreValor+" - "+ListaValores.getSelectedItem().toString());
            NombreValor = ListaValores.getSelectedItem().toString();            
            
            //Reiniciar Grill y Texto de URL
            URLDatos.setText("");
            reiniciarJTable(TablaHistorica);
            
            //Si hay un Valor Seleccionado
            if (!NombreValor.equals(""))
            {
                int Posicion;

                //Comprobamos que el Valor Exista en la BBDD
                if ((Posicion = DatosValores.BuscarValor(NombreValor)) != -1)
                {
                    //Nos Posicionamos en el Valor Seleccionado
                    PosicionarseEnValorNum(Posicion);
                }
            }
            //Establecemos la Activacion y Desactivacion de Botones
            ActivaDesactivaBotones();
        }
    }//GEN-LAST:event_ListaValoresItemStateChanged

    private void BMostrarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMostrarGraficoActionPerformed

        int RangoDias = Integer.parseInt(GraficoDias.getSelectedItem().toString());
        
        //Mostramos los Gráficos del Valor Seleccinado
        DatosHistoricos.MostrarGrafica(panelGrafico, lblGrafico, RangoDias, ChkCierre.isSelected(), ChkMinimo.isSelected(), ChkMaximo.isSelected(), ChkR2.isSelected(), ChkR1.isSelected(), ChkPivotP.isSelected(), ChkS1.isSelected(), ChkS2.isSelected());
    }//GEN-LAST:event_BMostrarGraficoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        NombreValor = ListaValores.getSelectedItem().toString();
        int NuevaPosicion;

        //Comprobamos que el Valor Exista en Memoria
        if ((NuevaPosicion = DatosValores.BuscarValor(NombreValor)) != -1)
        {
            //Borramos el Valor de la BBDD
            DatosValores.EliminarValor(NombreValor);
        
            //Actualizamos el Combo con los Datos de Memoria
            DatosValores.RellenaCombo(ListaValores);

            //Seleccionamos el Campo Anterior
            if (NuevaPosicion != 0)
                NuevaPosicion --;
            
            //Nos Posicionamos en el Campo Anterior
            PosicionarseEnValorNum(NuevaPosicion);
        }
        else
            System.out.println("El valor '"+NombreValor+"' No Existe en Memoria");
            
        //Establecemos la Activacion y Desactivacion de Botones
        ActivaDesactivaBotones();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ActManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActManualActionPerformed

    private void ActURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActURLActionPerformed

        //Obtenemos la Ruta de los Datos y el Rango de Fechas
        String DireccionURL = URLDatos.getText().toString();
        String FechaDesde   = ObtenerFechaDesde();
        String FechaHasta   = ObtenerFechaHasta();

        //Si hay una URL Especificada
        if (!DireccionURL.equals("") && !FechaDesde.equals("") && !FechaHasta.equals(""))
        {
            DireccionURL = DireccionURL + FechaDesde + "/" + FechaHasta;            
            System.out.println("Direccion '"+DireccionURL+"'");
            
            // Abrimos la URL y Cargamos los Datos
            if (DatosHistoricos.IncluirHistoricosURL(DireccionURL, NombreValor, RedondeoValor) == true)
            {
                DatosHistoricos.CargaGrill(TablaHistorica);
                RellenaTecnico();
            }
        }
    }//GEN-LAST:event_ActURLActionPerformed

    private void ChkCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkCierreActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkCierreActionPerformed

    private void ChkMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkMaximoActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkMaximoActionPerformed

    private void ChkMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkMinimoActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkMinimoActionPerformed

    private void ChkS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkS2ActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkS2ActionPerformed

    private void ChkS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkS1ActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkS1ActionPerformed

    private void ChkPivotPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkPivotPActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkPivotPActionPerformed

    private void ChkR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkR1ActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkR1ActionPerformed

    private void ChkR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkR2ActionPerformed
        
        CompruebaChecks();
    }//GEN-LAST:event_ChkR2ActionPerformed

    private void CompruebaChecks()
    {
        if (!ChkCierre.isSelected() && !ChkMinimo.isSelected() && !ChkMaximo.isSelected() &&
            !ChkS2.isSelected()     && !ChkS1.isSelected()     && !ChkPivotP.isSelected() &&
            !ChkR1.isSelected()     && !ChkR1.isSelected())
            BMostrarGrafico.setEnabled(false);
        else
            BMostrarGrafico.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public static void reiniciarJTable(javax.swing.JTable Tabla)
    {
        System.out.println("reiniciarJTable");
        String Cabecera[]={"Nombre", "Fecha", "Cierre", "Máximo", "Mínimo", "Variación", "%Var", "S2", "S1", "PivotP", "R1", "R2"};
        DefaultTableModel modelo = new DefaultTableModel(null, Cabecera);
        Tabla.setModel(modelo);
        int Anchos[]={120, 70, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50};
        
        //Establecemos el Tamaño de Cada Columna
        for (int i = 0; i < Tabla.getColumnCount(); i++)
            Tabla.getColumnModel().getColumn(i).setPreferredWidth(Anchos[i]);
    }
    
    public String ObtenerFechaHasta()
    {
        Calendar Calendario = Calendar.getInstance();
        return Calendario.get(Calendar.YEAR) + "-" + String.format("%02d", (Calendario.get(Calendar.MONTH) + 1)) + "-" + String.format("%02d", Calendario.get(Calendar.DATE));
    }
    
    public String ObtenerFechaDesde()
    {
        Calendar Calendario = Calendar.getInstance();
        return (Calendario.get(Calendar.YEAR)-1) + "-" + String.format("%02d", (Calendario.get(Calendar.MONTH) + 1)) + "-" + String.format("%02d", Calendario.get(Calendar.DATE));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActLocal;
    private javax.swing.JButton ActManual;
    private javax.swing.JButton ActURL;
    private javax.swing.JButton BMostrarGrafico;
    private javax.swing.JCheckBox ChkCierre;
    private javax.swing.JCheckBox ChkMaximo;
    private javax.swing.JCheckBox ChkMinimo;
    private javax.swing.JCheckBox ChkPivotP;
    private javax.swing.JCheckBox ChkR1;
    private javax.swing.JCheckBox ChkR2;
    private javax.swing.JCheckBox ChkS1;
    private javax.swing.JCheckBox ChkS2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JComboBox GraficoDias;
    private javax.swing.JButton Insertar;
    private javax.swing.JComboBox ListaValores;
    private javax.swing.JTable TablaHistorica;
    private javax.swing.JTabbedPane Tecnico;
    private javax.swing.JComboBox TecnicoDias;
    private javax.swing.JLabel TecnicoFecha;
    private javax.swing.JTextField TecnicoPP;
    private javax.swing.JTextField TecnicoR1;
    private javax.swing.JTextField TecnicoR2;
    private javax.swing.JTextField TecnicoS1;
    private javax.swing.JTextField TecnicoS2;
    private javax.swing.JTextField URLDatos;
    private javax.swing.JTextField ValorActual;
    private javax.swing.JTextField ValorMaximo;
    private javax.swing.JTextField ValorMinimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrafico;
    private javax.swing.JPanel panelGrafico;
    // End of variables declaration//GEN-END:variables
}
